const productos = [
    {
        id:'1',
        title: 'Remera BEE',
        price: '75',
        description: '',
        image: './assets/Remera1.jpeg',
        category:'black',
    },
    {
        id:'2',
        title: 'Remera IRISS',
        price: '92',
        description: '',
        image: './assets/Remera2.jpeg',
        category:'white',
    },    
    {
        id:'3',
        title: 'Remera DROP',
        price: '48',
        description: '',
        image: './assets/Remera3.jpeg',
        category:'black',
    },
    {
        id:'4',
        title: 'Remera ZULL',
        price: '37',
        description: '',
        image: './assets/Remera4.jpeg',
        category:'white',
    },
    {
        id:'5',
        title: 'Remera ROTTWEILER',
        price: '98',
        description: '',
        image: './assets/Remera5.jpeg',
        category:'black',
    },
    {
        id:'6',
        title: 'Remera SKUL',
        price: '76',
        description: '',
        image: './assets/Remera6.jpeg',
        category:'white',
    },
    {
        id:'7',
        title: 'Remera BOI',
        price: '51',
        description: '',
        image: './assets/Remera7.jpeg',
        category:'white',
    }
]